# Generated by Django 4.0.1 on 2022-01-31 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='functionalities',
        ),
        migrations.AddField(
            model_name='plan',
            name='functionalities',
            field=models.ManyToManyField(to='plans.Functionality'),
        ),
    ]
