# Generated by Django 4.0.1 on 2022-01-31 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_remove_plan_functionalities_plan_functionalities'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='functionality',
            table='functionality',
        ),
        migrations.AlterModelTable(
            name='plan',
            table='plan',
        ),
    ]
