# Generated by Django 4.0.1 on 2022-01-31 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_alter_functionality_table_alter_plan_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='functionality',
            table=None,
        ),
        migrations.AlterModelTable(
            name='plan',
            table=None,
        ),
    ]
