# Generated by Django 4.0.1 on 2022-01-31 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_rename_teste_plan_functionalities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='functionalities',
            field=models.ManyToManyField(related_name='Functionalities', to='plans.Functionality', verbose_name='Funcionalidades'),
        ),
    ]
