# Generated by Django 4.0.1 on 2022-01-31 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_alter_plan_functionalities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionality',
            name='price_fixed',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço Fixo'),
        ),
        migrations.AlterField(
            model_name='functionality',
            name='price_student',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço por Estudante'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price_fixed',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço Fixo'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price_student',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço por Estudante'),
        ),
    ]
