# Generated by Django 4.0.1 on 2022-01-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0009_alter_plan_functionalities_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='functionalities_remove',
            field=models.ManyToManyField(blank=True, related_name='functionalities_remove', to='plans.Functionality', verbose_name='Funcionalidades Não Removidas'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='functionalities',
            field=models.ManyToManyField(related_name='functionalities', to='plans.Functionality', verbose_name='Funcionalidades'),
        ),
    ]
