# Generated by Django 4.0.1 on 2022-02-02 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0010_plan_functionalities_remove_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='functionalities_remove',
        ),
    ]
